vim.g.python_host_prog = 'Users/rajnandinimukherjee/my-venv/bin/python'
vim.g.black_virtualenv = '/Users/rajnandinimukherjee/my-venv/bin/black'
require('base')
require('maps')
require('plugins')
require('p-tree')
require('p-lsp')
require('p-mason')
require('color')
require('text')
require('p-lualine')
require('p-telescope')
require('p-bookmark')
require('p-lspkind')
require('p-cmp')
require('p-tex')
require('p-dashboard')
require('p-session')
require('p-black')
