vim.g.python3_host_prog = '/usr/local/bin/python3'
require('base')
require('maps')
require('plugins')
require('p-tree')
require('p-lsp')
require('p-mason')
require('color')
require('text')
require('p-lualine')
require('p-telescope')
require('p-bookmark')
require('p-lspkind')
require('p-cmp')
require('p-tex')
require('p-dashboard')
require('p-session')
